ARG VERSION=latest

ARG NODE_ENV=production

ENV NODE_ENV=$NODE_ENV

ENV PORT=8080

FROM node:$VERSION

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY app/package.json app/package-lock.json* /usr/src/app/

RUN cd /usr/src/app/ && NODE_ENV=$NODE_ENV npm install

COPY app/ /usr/src/app/

EXPOSE 8080

CMD [ "npm", "start" ]